version: '3'

services:
  telegabot:
    image: dzhoonk/loltelebot
    environment:
      BOT_TOKEN: "5033258071:AAHHZG1B-wAYta70zKGJguVTyujYlTncPKU"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
