name: DockerPusher

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'
    
jobs:
  on-success:
    name: Publish image to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Publish image to Docker'
          repo-token: ${{ secrets.WORKFLOW_TOKEN }}
          wait-interval: 10
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/loltelebot:latest
